language: java
sudo: required
git:
  depth: false
addons:
  sonarcloud:
    organization: "vatbub-github"
jdk:
  - openjdk14
cache:
  directories:
  - "$HOME/.m2"
install:
- curl https://cli-assets.heroku.com/install.sh | sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -DtrimStackTrace=false --settings travisMavenSettings.xml
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then heroku plugins:install java; heroku deploy:jar standaloneserverlauncher/target/matchmaking.standalone-server-launcher-1.0-SNAPSHOT-jar-with-dependencies.jar --app vatbubmatchmakingstaging; fi
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
